version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=user-db
      - DB_PORT=3306
      - DB_DATABASE=user_service
      - DB_USERNAME=user_service
      - DB_PASSWORD=user_service_pass
    ports:
      - "8001:8000"
    depends_on:
      - user-db
    networks:
      - microservice-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=order-db
      - DB_PORT=3306
      - DB_DATABASE=order_service
      - DB_USERNAME=order_service
      - DB_PASSWORD=order_service_pass
    ports:
      - "8002:8000"
    depends_on:
      - order-db
    networks:
      - microservice-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=product-db
      - DB_PORT=3306
      - DB_DATABASE=product_service
      - DB_USERNAME=product_service
      - DB_PASSWORD=product_service_pass
    ports:
      - "8003:8000"
    depends_on:
      - product-db
    networks:
      - microservice-network

  user-db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=user_service
      - MYSQL_USER=user_service
      - MYSQL_PASSWORD=user_service_pass
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - microservice-network

  order-db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=order_service
      - MYSQL_USER=order_service
      - MYSQL_PASSWORD=order_service_pass
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - microservice-network

  product-db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=product_service
      - MYSQL_USER=product_service
      - MYSQL_PASSWORD=product_service_pass
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - product-db-data:/var/lib/mysql
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  user-db-data:
  order-db-data:
  product-db-data: